server {
    listen 80;
    server_name _;

    client_max_body_size 100m;
    sendfile on;
    tcp_nopush on;
    gzip on;
    gzip_types text/css application/javascript application/json;

    root /usr/share/nginx/html;

    location = / {
        return 302 /congat/;
    }

    location /congat/ {
        try_files $uri $uri/ /congat/index.html;
    }

    location /congat/assets/ {
        try_files $uri =404;
        expires 7d;
        add_header Cache-Control "public, immutable";
    }
}
